---
title: "PlotlyTest"
author: "Callum Gapes"
date: "2025-04-08"
output: html_document
---

```{r setup}
library(dplyr)
library(plotly)
library(ggplot2)

source("R Files/shorebirdFunctions.R")
source("R Files/plotDefaults.R")

df.alltags <- readRDS("Data/df.alltags.rds")
```


```{r Using ggplotly}
# Choose tag to plot
currentTagID <- 60472
## Choose time range to plot
# Set completeTimeRange to 1 to plot all detections for the tag
completeTimeRange <- 1
# User-defined start and end time - in AEST
# Curlew Plot 1
#timeStart <- "2023-03-27 00:00:00"
#timeEnd <- "2023-03-29 24:00:00"
#sunReceiver <- "Milham's Pond"
# Curlew Plot 2
#timeStart <- "2023-04-10 00:00:00"
#timeEnd <- "2023-04-14 24:00:00"
#sunReceiver <- "Milham's Pond"
# Curlew Plot 3
timeStart <- "2023-04-20 00:00:00"
timeEnd <- "2023-04-23 24:00:00"
sunReceiver <- "Fullerton Entrance"

# Graphical Options - General
pointSize <- 1.5
showPlotTitle <- 0

# Sunrise and Sunset Graphical Options
plotSun <- 1 # Sunrise and sunset vertical lines
sunriseColour = "#ff9933"
sunsetColour = "#530066"
sunLineAlpha = 1
sunLineWidth = 1
sunFillAlpha = 0.06
sunLineType = "longdash"

# Receiver for sunrise/set
#sunReceiver <- "Milham's Pond"
#sunReceiver <- "Fullerton Entrance"

# Graphical Options - Tide
plotTidalCurve <- 1 # Interpolated tidal curve
plotTide <- 0 # High and low tide vertical lines
tideColour = "#61caff"
tideLineWidth = 2
tideAlpha = 0.6

# Graphical Options - Font
fontSizeAxisTitle = 14
fontSizeAxisTicks = 10
fontSizeLegendTitle = 13 
fontSizeLegendLabels = 11

paddingAxisTitle = 10

#### End of User Input ####

# Set start and end time for plot
if (completeTimeRange) {
  # Get time interval from first and last detections
  timeStart <- min(filter(df.alltags,motusTagID == currentTagID)$timeAus)
  timeEnd <- max(filter(df.alltags,motusTagID == currentTagID)$timeAus)
} else{
  timeStart <- ymd_hms(timeStart ,tz = "Australia/Sydney")
  timeEnd <- ymd_hms(timeEnd ,tz = "Australia/Sydney")
}

# Filter by tag and time interval
tmp <- filter(df.alltags, motusTagID == currentTagID, timeAus >= timeStart, timeAus <= timeEnd)

# Get sunrise and sunset times during time interval
plot.sunrise <- (tmp %>% filter(recvDeployName==sunReceiver) %>% dplyr::select(sunrise) %>% unique())$sunrise
plot.sunset <- (tmp %>% filter(recvDeployName==sunReceiver) %>% dplyr::select(sunset) %>% unique())$sunset

# Create plot
p <- tmp %>%  
  ggplot(aes(timeAus, sigPositive)) # x-axis = signal strength, y-axis = time
  
  # Add tidal curve
if (plotTidalCurve) {
  p <- plot.addTidalCurve(p)
}
  
  ## Gridlines and background
  p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  
  # Plot points
  geom_point(aes(colour = recvDeployName, shape = recvDeployName), 
             size = pointSize) +
             #size = pointSize, 
             #shape = pointShape) + 
  
  ## Automatic legend
  labs(colour = "Receiver", shape = "Receiver") + # Legend title
  theme(legend.text = element_text(size = fontSizeLegendLabels),
        legend.title = element_text(size = fontSizeLegendTitle)) +  
  
  ## Manually labelled legend
  #scale_colour_discrete(name = "Receiver",
   #                     labels = c("Fullerton Entrance", "Milham's Pond")) +
  #  scale_shape_discrete(name = "Receiver",
   #                     labels = c("Fullerton Entrance", "Milham's Pond")) +
  
  guides(colour = guide_legend(order = 1, byrow = TRUE), shape = guide_legend(order = 1, byrow = TRUE)) + # Make this legend appear first
  
  ## Axes
  ylab("Signal Strength") + 
  xlab("Date (AEST)") +
  xlim(timeStart,timeEnd) +
  theme(axis.line.x = element_line(linewidth = 1, colour = "black"), 
        axis.title.x = element_text(size = fontSizeAxisTitle, margin = margin(t = paddingAxisTitle)),
        axis.text.x = element_text(size = fontSizeAxisTicks),
        
        axis.line.y.left = element_line(linewidth = 1, colour = "black"),
        axis.line.y.right = element_line(linewidth = 1, colour = tideColour),
        axis.title.y = element_text(size = fontSizeAxisTitle, margin = margin(r = paddingAxisTitle)),
        axis.text.y = element_text(size = fontSizeAxisTicks),
        legend.spacing.y = unit(8,'pt'),
        legend.position = "none") +
    scale_x_datetime(breaks = "12 hours",expand = c(0,0), date_labels = "%e %b\n%H:%M")
  
ggplotly(p)
```

```{r Test Directly with Plotly}
p <- plot_ly(tmp, x = ~timeAus, y = ~sigPositive, type = 'scatter', mode = 'markers') %>%
    layout(
        xaxis = list(
            type = "date",
            tickformat = "%H:%M"
        )
    )

p <- layout(p, xaxis = list(
  type = "date",           # Force datetime axis
  dtick = "H12",           # 12-hour tick spacing
  tickformat = "%d/%m %H:%M",  # Day/Month Hour:Minute
  range = c("2023-03-27 00:00:00", "2023-04-01 00:00:00")
))

p
```

