---
title: "ExploreReceiverDatabase"
author: "Callum Gapes"
date: "2025-04-08"
output: html_document
---

```{r Explore a Single Table}
tbl_of_interest <- "activity"
#recv_of_interest <- "SG-61F1RPI3C8AB"
recv_of_interest <- df.serno[9,1]

recv.db <- dbConnect(SQLite(), paste("Data/motus_receiver_data/",recv_of_interest,".motus",sep=""))
tbl.recv <- tbl(recv.db, tbl_of_interest)
df.recv <- tbl.recv %>% as.data.frame()

df.recv %>% str()

# Check how many hourBin there are for each day
sum.day <- df.recv %>% group_by(year, month, day) %>% summarise(
  n = n(), 
  .groups = "drop")

print(paste("There are", nrow(sum.day),"days of detection data"))

sum.bin <- df.recv %>% group_by(year, month, day, hourBin) %>% summarise(
  n = n(), 
  .groups = "drop")

# Add start time of period (UTC)
sum.bin <- sum.bin %>% mutate(
  binStart = as.POSIXct(hourBin * 3600, tz = "UTC"),
  binEnd = as.POSIXct((hourBin + 1) * 3600, tz = "UTC")
)

all_bins <- data_frame(
  binStart = seq(from = min(sum.bin$binStart),
                 to = max(sum.bin$binStart),
                 by = "hour")
    ,
  binEnd = seq(from = min(sum.bin$binEnd),
                 to = max(sum.bin$binEnd),
                 by = "hour")
  )

all_bins <- all_bins %>% mutate(
  binStart = as.POSIXct(binStart, tz ="UTC") %>% with_tz(tzone = "Australia/Sydney"),
  binEnd = as.POSIXct(binEnd, tz ="UTC") %>% with_tz(tzone = "Australia/Sydney")
)

sum.bin$present <- 1

uptime <- all_bins %>%
  left_join(sum.bin[, c("binStart", "present")], by = "binStart") %>%
  mutate(present = ifelse(is.na(present), 0, present))

# Check station of deployment / check for multiple deployments
tmp.stations <- recv.db %>% tbl("recvDeps") %>% as.data.frame() %>% select(stationName)
print(tmp.stations)
```

```{r GGplot ChatGPT}
if(nrow(tmp.stations) == 1){
   

ggplot(sum.bin) +
  geom_segment(aes(x = binStart, xend = binEnd, y = 1, yend = 1), 
               linewidth = 4, colour = "steelblue") +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m\n%Y") +
  theme_minimal() +
  labs(title = paste(sep = "", "Receiver Uptime For ", tmp.stations$stationName[1]," (",recv_of_interest,")"), x = "Time", y = NULL) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
} else {
  print("Error, multiple station deployments for this receiver")
}

```

```{r Consider All Receivers (by using entire motus db instead of single receiver)}
# Some sites have had multiple receivers; the uptime for the SITE should take into account all receivers that have been deployed there
# Therefore see if can filter by site name instead of receiver ID

#tbl_of_interest <- "activity"
tbl_of_interest <- "recvdeps"

motusData <- dbConnect(SQLite(), "Data/project-294.motus")
tbl.activity <- tbl(motusData, tbl_of_interest)
df.activity <- tbl.activity %>% as.data.frame()

df.activity %>% head()
```



