---
title: "Nocturnal_Roost_Switching"
author: "Callum Gapes"
date: "2025-04-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r October - November Plot}
# Choose species to plot
currentSpecies <- "Red-necked Avocet"
#currentSpecies <- "Bar-tailed Godwit"
#currentSpecies <- "Pacific Golden-Plover"

## Choose time range to plot
# Set completeTimeRange to 1 to plot all detections for the tag
completeTimeRange <- 0 
# User-defined start and end time
timeStart <- "2023-10-28 00:00:00"
timeEnd <- "2023-11-01 24:00:00"

# Graphical options
plotTidalCurve <- 1
plotSun <- 1
plotTide <- 0
pointSize <- 1

tideColour = "#61caff"
tideLineWidth = 1
tideAlpha = 0.6

sunriseColour = "#ff9933"
sunsetColour = "#530066"

fontSizeAxisTitle = 13
fontSizeAxisTicks = 10
fontSizeLegendTitle = 12 
fontSizeLegendLabels = 11
paddingAxisTitle = 10

# Set receiver for sunrise/set times
sunReceiver <- "Curlew Point"

# Set receivers to exclude from output
recvExclude = c("Swan Pond", "Fullerton Entrance")

# Get sunrise and sunset times during time interval
plot.sunrise <- (tmp %>% filter(recvDeployName==sunReceiver) %>% dplyr::select(sunrise) %>% unique())$sunrise
plot.sunset <- (tmp %>% filter(recvDeployName==sunReceiver) %>% dplyr::select(sunset) %>% unique())$sunset

# Set start and end time for plot
if (completeTimeRange) {
  # Get time interval from first and last detections
  timeStart <- min(df.alltags$timeAus)
  timeEnd <- max(df.alltags$timeAus)
} else{
  timeStart <- ymd_hms(timeStart, tz = "Australia/Sydney")
  timeEnd <- ymd_hms(timeEnd, tz = "Australia/Sydney")
}

# Filter by time interval and species
tmp <- filter(df.alltags, speciesEN == currentSpecies, timeAus >= timeStart, timeAus <= timeEnd)

# Exclude specific stations
tmp <- tmp %>% filter(!recvDeployName %in% recvExclude)

# Manually remove swan pond
#tmp <- filter(tmp, recvDeployName != "Swan Pond")

p <- tmp %>% 
  ggplot(aes(x = timeAus, y = sigPositive)) + # x-axis = signal strength, y-axis = time
  
  # Plot points
  geom_point(aes(colour = as.character(motusTagID)),
                 shape = pointShape,
                 size = pointSize) + # 
  
  # Grid by receiver
  facet_grid(vars(recvDeployName), switch = "both") +
  #facet_wrap(~factor(recvDeployName, levels = c("Tomago","Fullerton Cove","Curlew Point")), dir = "v", strip.position = "right") +
  
  # Legend
  labs(colour = "Motus Tag ID", ) + 
  guides(colour = guide_legend(order = 1)) + # Make this legend appear first


  # Axis titles
  ylab("Signal Strength") + 
  xlab("Date-Time") +
  
  # Font Size
  theme_gray(base_size = 14) +
  
  ## Automatic title 
  #ggtitle(paste("Detections for",currentSpecies)) + theme(plot.title = element_text(hjust = 0.5), legend.justification = c("right","top"))+  # Plot title

    ## Gridlines and background
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  ## Custom title
  # ggtitle("Pied Stilt Detections") + theme(plot.title = element_text(hjust = 0.5)) # Plot title
  
  scale_x_datetime(breaks = "12 hours",expand = c(0,0), date_labels = "%e %b\n%H:%M")

  
# Add sunset and sunrise
if (plotSun) {
  p <- plot.addSunriseSet(p)
}

# Add high and low tides
if (plotTide) {
  p <- plot.addTideHighLow(p)
}

# Add tidal curve
if (plotTidalCurve) {
  p <- plot.addTidalCurve(p)
}

if (plot.sunrise[1]<plot.sunset[1]){
  # Lower xlim to first sunrise
  p <- p + annotate(geom = "rect", xmin = timeStart, xmax = plot.sunrise[1], ymin = -Inf, ymax = Inf, fill = sunsetColour, alpha = sunFillAlpha)
  
  # Check if equal number of sunrises and sunsets
  if (length(plot.sunrise) == length(plot.sunset)){
    
    # All sunrise -> sunset
    p <- p + annotate(geom = "rect", xmin = plot.sunrise, xmax = plot.sunset, ymin = -Inf, ymax = Inf, fill = sunriseColour, alpha = sunFillAlpha)
    
    # Sunset -> sunrise (excluding last)
    p <- p + annotate(geom = "rect", xmin = plot.sunset[1:length(plot.sunset)-1], xmax = plot.sunrise[2:length(plot.sunrise)], ymin = -Inf, ymax = Inf, fill = sunsetColour, alpha = sunFillAlpha)
    
    # Last sunset -> upper xlim
    p <- p + annotate(geom = "rect", xmin = plot.sunset[length(plot.sunset)], xmax = timeEnd, ymin = -Inf, ymax = Inf, fill = sunsetColour, alpha = sunFillAlpha)
  }
  else{
    ### To Do
  }
}

  
p
```

```

