---
title: "Shorebird_Monitoring_NSW_Callum"
author: "Callum Gapes"
date: "2023-08-14"
output:
  word_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: inline
---

# Shorebird_Monitoring_NSW.Rmd
## Setup RStudio and Load Packages
```{r setup Packages include = False}
#rm(list = ls()) # Clear environment
Sys.setenv(TZ="UTC") # Set timezone to UTC

library(lubridate)
library(motus)
library(dplyr)
library(DBI)
library(RSQLite)
library(lutz)
library(ggplot2)
library(crayon)
library(tidyverse)
library(rnaturalearth)
library(ggmap)
library(sf) # Spatial vector data
library(suntools) # Sunrise/set info
library(ggnewscale)
library(viridis)
library(ISLR)
library(flexmix)
library(caret)
library(scales) # Display values as percentages
library(OpenImageR) # Read images
library(kableExtra) # Produce nicely formatted tables
library(shiny) # Interactive plots / user input
library(gganimate)
library(gifski)
library(terra)
library(prismatic)
library(genTS)
library(DescTools)
library(RSQLite) # To fix error code that was occurring on Motus import
library(ggeasy)
library(bioRad) # Find sunrise and sunset at coordinates
library(forcats) # Reorder factor levels
library(Hmisc) # Installed for bar plot error bars
library(rstatix) # Easy calculation of statistical summaries
library(kableExtra) # Produce nicely formatted tables
library(scales) # Display values as percentages
library(fuzzyjoin)
library(plotly)
library(DT)

source("R Scripts/shorebirdFunctions.R")
```


```{r Load Shorebird Data From File}
df.alltags <- readRDS("Data/df.alltags.rds")
receiverSummary <- readRDS("Data/receiverSummary.rds")
tagSummary <- readRDS("Data/tagSummary.rds")
tidalCurve <- readRDS("Data/tidalCurve.rds")
tideData <- readRDS("Data/tideData.rds")
#station_rename_map <- readRDS("Data/station_rename_map.rds")
df.recvDeps <- readRDS("Data/df.recvDeps.rds")
```


## Plot Default Formatting
```{r Plot-Options}
## Default options for plots
plotSun <- 0
plotTide <- 0
plotTidalCurve <- 1
completeTimeRange <- 0

sunriseColour = "orange"
sunsetColour = "purple"
sunLineAlpha = 0.6
sunLineWidth = 1
sunLineType = "longdash"

highTideColour = "blue"
lowTideColour = "#61caff"
#tideColour = "blue"
tideColour = "#61caff"
tideLineWidth = 0.5
tideAlpha = 0.3

vlineAlpha <- 0.3
vlineWidth <- 1
pointSize <- 1.2
pointShape <- "circle"

fontSizeAxisTitle = 14
fontSizeAxisTicks = 10
fontSizeLegendTitle = 13 
fontSizeLegendLabels = 11
paddingAxisTitle = 10
```

```{r Import-Shorebird-Data }
# if (newDetection == TRUE){
#   ## If motus database has been updated / there is new detection data
#   print("Checking Motus Database for Updates")
#   # Download new detections from Motus
#   source("R Files/updateMotusDatabase.R") 
#   # Convert to data frame, filter spurious detections, add sun and tidal data
#   source("R Files/importShorebirdData.R") 
#   
# } else if (newDetection == FALSE){
#   print("Loading Shorebird Data From File")
#   load(file = "Data/NSW_Shorebird_Data.RData")
# } 
```

```{r Export Receiver Info to Table}
tbl.receiver <- receiverSummary %>% dplyr::select(recvDeployName, lat, lon)


tbl.receiver <- data.frame(lapply(tbl.receiver, function(x) {
  if (is.list(x)) {
    return(sapply(x, toString))
  } else {
    return(x)
  }
}), stringsAsFactors = FALSE)

#tbl.receiver %>% write.csv(file = "ReceiverInfo.csv")
tbl.receiver %>% write.csv(file = "C:/Users/callu/Documents/Shorebird Monitoring NSW/GIS Map/Map Data/ReceiverInfo.csv")
```





