---
title: "Signal_Strength_Variation"
author: "Callum Gapes"
date: "2023-11-07"
output: html_document
---

# Description

This file looks at variation in signal strength.
Haven't looked at it recently

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# ---- Load Packages ----
library(dplyr)

# ---- Load Data ----
df.alltags <- readRDS("Data/df.alltags.rds")
```

```{r Load Data}
# Filter detections to only those +- 1 hour of high or low tide.
df.highLowDetections <- df.alltags %>% filter(abs(tideTimeDiff) <= 1) %>% 
  select(sig, motusTagID, recvDeployName, tideDateTimeAus, tideCategory, timeAus, speciesEN) %>% 
  group_by(motusTagID, recvDeployName, tideDateTimeAus, tideCategory, speciesEN) %>% 
  summarise(sigMean = mean(sig), sigVar = var(sig), .groups = "drop")
```

```{r One-way ANOVA - Single Species, Single Receiver (High/Low Tide)}
# Select species and receiver
tmp.receiver <- "Fullerton Entrance"
tmp.species <- "Pied Stilt"

# Filter detections by species and receiver
tmp.detections <- df.highLowDetections %>% filter(speciesEN == tmp.species, recvDeployName == tmp.receiver) 
# Run ANOVA on one species at one site
res_aov <- aov(data = tmp.detections, sigVar ~ tideCategory)
res_aov %>% summary()

# Assumption check
# Normality
qqnorm(tmp.detections$sigVar)
shapiro.test(tmp.detections$sigVar)

# Homogeneity of variances
bartlett.test(data = tmp.detections, sigVar ~ tideCategory)
```

```{r Two-way ANOVA - Single Species (High/Low Tide and Receiver)}
# Select species and filter
tmp.species <- "Pied Stilt"

# Run ANOVA on one species (across all sites)
tmp.detections <- df.highLowDetections %>% filter(speciesEN == tmp.species) 

# Run Two-way Anova
res_aov <- aov(data = tmp.detections, sigVar ~ tideCategory * recvDeployName)
res_aov %>% summary()
```

```{r Misc/Testing}
# Import tide data and format time stamps
tideData <- read.csv("Data/Tide/TideDataNewcastle2023.csv") %>% select(tideHeight, tideDateTimeAus, high_low)
tideData$tideDateTimeAus <- ymd_hms(tideData$tideDateTime, tz = "Australia/Sydney")

# Set start and end time
timeStart <- "2023-10-28 00:00:00" %>% ymd_hms(tz = "Australia/Sydney")
timeEnd <- "2023-10-31 24:00:00" %>% ymd_hms(tz = "Australia/Sydney")

# Filter by time range
tideData <- tideData %>% filter(tideDateTimeAus >= timeStart & tideDateTimeAus <= timeEnd)

# Tag ID
tmp.ID <- 60470

for (i in 1:nrow(tideData)) {
  currentTideTime <- tideData$tideDateTimeAus[i]
  tmp.detections <- df.alltags %>% filter(timeAus >= (currentTideTime - hours(1)) & timeAus <= (timeEnd + hours(1)) & motusTagID == tmp.ID)
  tmp.var <- var(tmp.detections$sig)
  print(tmp.var)
}

tideData <- tideData %>% rowwise() %>% mutate(numDetections = 
                                                nrow(df.alltags %>% filter(timeAus >= (tideDateTimeAus - hours(1)) & timeAus <= (tideDateTimeAus + hours(1)) & motusTagID == tmp.ID)),
                                              sigMean = (df.alltags %>% filter(timeAus >= (tideDateTimeAus - hours(1)) & timeAus <= (tideDateTimeAus + hours(1)) & motusTagID == tmp.ID))$sig %>% mean(),
                                              sigVar = (df.alltags %>% filter(timeAus >= (tideDateTimeAus - hours(1)) & timeAus <= (tideDateTimeAus + hours(1)) & motusTagID == tmp.ID))$sig %>% var())

test <- tideData %>% select(tideDateTimeAus, high_low) 
test <- test %>% expand_grid(tagInfo$motusTagID, receiverInfo$recvDeployName)
test <- test %>% rename("motusTagID" = "tagInfo$motusTagID", "recvDeployName" = "receiverInfo$recvDeployName")

test <- test %>% rowwise() %>% mutate(numDetections = nrow(df.alltags %>% filter(timeAus >= (tideDateTimeAus - hours(1)) & timeAus <= (tideDateTimeAus + hours(1)) & motusTagID == motusTagID & recvDeployName == recvDeployName)))

df.alltags %>% 
  select(sig, motusTagID, recvDeployName, tideCategoryTime, timeAus) %>% 
  group_by(motusTagID, recvDeployName, tideCategoryTime) %>% 
  filter()
 
# Filter detections to only those +- 1 hour of high or low tide.
tmp <- df.alltags %>% filter((tideCategory == "High" | tideCategory == "Low") & abs(timeSinceTideCategory) <= 1)
tmp2 <- tmp %>% select(sig, motusTagID, recvDeployName, tideCategoryTime, tideCategory, timeAus, speciesEN)
tmp3 <- tmp2 %>% group_by(motusTagID, recvDeployName, tideCategoryTime, tideCategory, speciesEN)

tmp.sum <- tmp3 %>% summarise(sigMean = mean(sig), sigVar = var(sig))

# Run ANOVA on one species at one site
tmp.receiver <- "Barry_Fullerton_cove"
tmp.species <- "Pied Stilt"

tmp4 <- tmp.sum %>% filter(speciesEN == tmp.species, recvDeployName == tmp.receiver) 

res_aov <- aov(data = tmp4, sigVar ~ tideCategory)
res_aov %>% summary()

# Run ANOVA on one species (across all sites)
tmp4 <- tmp.sum %>% filter(speciesEN == tmp.species) 

res_aov <- aov(data = tmp4, sigVar ~ tideCategory * recvDeployName)
res_aov %>% summary()

#tagID <- 

```


