---
title: "Summaries_And_Tables"
author: "Callum Gapes"
date: "2023-11-10"
output: html_document
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("C:/Users/callu/Documents/Shorebird Monitoring NSW")
knitr::opts_knit$set(root.dir = "C:/Users/callu/Documents/Shorebird Monitoring NSW")

# ---- Load Packages ----
library(dplyr)
library(DT) # Datatable for interactive tables
library(sf)
library(kableExtra)
library(lubridate) # Working with datetimes
library(scales) # Display values as percentages
library(purrr)

# ---- Load Custom Functions ----
source(here("R Files", "shorebirdFunctions.R"))

# ---- Load Data ----
df.alltags <- readRDS("Data/df.alltags.rds")
tagSummary <- readRDS("Data/tagSummary.rds")
receiverSummary <- readRDS("Data/receiverSummary.rds")
df.recvDeps <- readRDS("Data/df.recvDeps.rds")
speciesSummary <-readRDS("Data/speciesSummary.rds")
```

```{r Nicely Formatted Tag Summary}
tmp.tagSummary <- tagSummary %>% dplyr::select(motusTagID, speciesEN, recentDetectionAus, firstDetectionAus, detectionDays, detectionProportion) %>% mutate(firstDetectionAus = as.Date(firstDetectionAus), recentDetectionAus = as.Date(recentDetectionAus), detectionProportion = percent(detectionProportion)) %>% relocate(firstDetectionAus, .before = recentDetectionAus) %>% arrange(desc(recentDetectionAus)) %>% rename("Species" = "speciesEN", "First Detection" = "firstDetectionAus", "Last Detection" = "recentDetectionAus", "Days Detected" = "detectionDays", "Rate" = "detectionProportion")

kable(tmp.tagSummary, align = "l") %>% kableExtra::kable_styling()
```

```{r Tag Summary - From 1st July 2024}
start_date <- as.Date("2024-07-01")

tmp.tagSummary <- tagSummary %>%
  filter(recentDetectionAus >= start_date) %>% 
  dplyr::select(motusTagID, 
                speciesEN, 
                recentDetectionAus, 
                firstDetectionAus, 
                detectionDays, 
                detectionProportion) %>% 
  mutate(firstDetectionAus = as.Date(firstDetectionAus), 
         recentDetectionAus = as.Date(recentDetectionAus), 
         detectionProportion = percent(detectionProportion)) %>% 
  relocate(firstDetectionAus, .before = recentDetectionAus) %>% 
  arrange(desc(recentDetectionAus)) %>% 
  rename("Species" = "speciesEN", 
         "First Detection" = "firstDetectionAus", 
         "Last Detection" = "recentDetectionAus", 
         "Days Detected" = "detectionDays", 
         "Proportion of Days Detected" = "detectionProportion")

kable(tmp.tagSummary, align = "c") %>% kableExtra::kable_styling()

```


```{r Nicely Formatted Tag Summary - Single Species}
tmp.species <- "Bar-tailed Godwit"
tmp.tagInfo <- tagSummary %>% filter(speciesEN == tmp.species) %>% dplyr::select(motusTagID, recentDetectionAus, firstDetectionAus, detectionDays, detectionProportion) %>% rename("First_Detection" = "firstDetectionAus", "Last_Detection" = "recentDetectionAus", "Days_Detected" = "detectionDays", "Rate" = "detectionProportion") %>% mutate(First_Detection = as.Date(First_Detection), Last_Detection = as.Date(Last_Detection), Rate = percent(Rate)) %>% relocate(First_Detection, .before = Last_Detection)

kable(tmp.tagInfo, align = "l") %>% kableExtra::kable_styling()
```

```{r Receiver Summary}
tmp.receiverSummary <- receiverSummary %>% dplyr::select(recvDeployName, firstDetectionAus, recentDetectionAus, uniqueTags, species) %>% mutate(firstDetectionAus = as.Date(firstDetectionAus), recentDetectionAus = as.Date(recentDetectionAus)) %>%  rename("Receiver" = "recvDeployName", "First Detection" = "firstDetectionAus", "Last Detection" = "recentDetectionAus", "Unique Tags" = "uniqueTags") %>% arrange(desc(`Last Detection`))

# Manually remove receivers
tmp.receiverSummary <- tmp.receiverSummary %>% filter(Receiver != "Davies Point" & Receiver != "Corrie Island")
#tmp.receiverSummary$lon[7] = 151.6811

kable(tmp.receiverSummary, align = "l") %>% kableExtra::kable_styling()
```

```{r Receiver Summary - Specific Date Range - Pre Activity Attempt}
print("Generating detection summary for each receiver")

start_date <- as.Date("2024-07-01")

df.alltags.tmp <- df.alltags %>% filter(
  dateAus >= start_date
)

# Get list of receivers from the raw receiver summary.
# This is to include all receivers (find better way of doing this later)

#receiverList <- df.alltags.tmp$recvDeployName %>% unique()
receiverList <- receiverSummary$recvDeployName
receiverCount <- receiverList %>% length()

# Create empty data frame to use for the summary
tmp.receiverSummary <- as.data.frame(receiverList)
colnames(tmp.receiverSummary) <- c("recvDeployName")

for (i in 1:receiverCount) {
  # Get the first and most recent detections for each station.
  # Note: suppressWarnings is used for warning message regarding NA values (station with no detections)
  tmp.receiverSummary$recentDetection[i] <- df.alltags.tmp %>% filter(recvDeployName == receiverList[i]) %>% dplyr::select(ts) %>% max() %>% suppressWarnings()
  tmp.receiverSummary$firstDetection[i] <- df.alltags.tmp %>% filter(recvDeployName == receiverList[i]) %>% dplyr::select(ts) %>% min() %>% suppressWarnings()
}

# Convert detection times to Australian (Sydney) timezone
tmp.receiverSummary <- mutate(tmp.receiverSummary, 
                       recentDetectionAus = recentDetection %>% as_datetime(tz = "Australia/Sydney"),
                       firstDetectionAus = firstDetection %>% as_datetime(tz = "Australia/Sydney"))

# Remove columns with original integer time value
tmp.receiverSummary <- tmp.receiverSummary %>% dplyr::select(recvDeployName, firstDetectionAus, recentDetectionAus)

# Sort by most recent detection
tmp.receiverSummary <- tmp.receiverSummary %>% arrange(desc(recentDetectionAus))

# Count the number of unique tags detected by each station, and add to the data frame.
tmp.receiverSummary <- left_join(tmp.receiverSummary, df.alltags.tmp %>% 
                            count(recvDeployName,motusTagID) %>% 
                            count(recvDeployName) %>% 
                            rename("uniqueTags"="n"), by = "recvDeployName")

# Add list of species that the receiver has detected
tmp.receiverSummary <- cbind(tmp.receiverSummary, species = NA)
for (i in 1:nrow(tmp.receiverSummary)){
  tmp.receiverSummary$species[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(speciesEN) %>% unique() %>% list()
}

# Add list of tags that the receiver has detected
tmp.receiverSummary <- cbind(tmp.receiverSummary, motusTagID = NA)
for (i in 1:nrow(tmp.receiverSummary)){
  tmp.receiverSummary$motusTagID[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(motusTagID) %>% unique() %>% list()
}

# Adding lat and long
for (i in 1:receiverCount) {
  tmp.receiverSummary$lat[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(recvDeployLat) %>% unique()
  tmp.receiverSummary$lon[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(recvDeployLon) %>% unique() 
}

# Add list of serno's and motus device IDs that have been deployed for the station name (recvDeployName)
for (i in 1:receiverCount){
  tmp.receiverSummary$sernos[i] <- df.recvDeps %>% 
    filter(stationName == tmp.receiverSummary$recvDeployName[i]) %>% 
    select(serno) %>% 
    unique()
  
  tmp.receiverSummary$deviceIDs[i] <- df.recvDeps %>% 
    filter(stationName == tmp.receiverSummary$recvDeployName[i]) %>% 
    select(deviceID) %>% 
    unique()
  
  tmp.receiverSummary$deployIDs[i] <- df.recvDeps %>% 
    filter(stationName == tmp.receiverSummary$recvDeployName[i]) %>% 
    select(deployID) %>% 
    unique()
}

tmp.receiverSummary <- tmp.receiverSummary %>% 
  dplyr::select(recvDeployName, 
                firstDetectionAus, 
                recentDetectionAus, 
                uniqueTags, 
                species) %>% 
  mutate(firstDetectionAus = as.Date(firstDetectionAus), 
         recentDetectionAus = as.Date(recentDetectionAus)) %>%  
  rename("Receiver" = "recvDeployName", 
         "First Detection" = "firstDetectionAus", 
         "Last Detection" = "recentDetectionAus", 
         "Unique Tags" = "uniqueTags",
         "Species" = "species") %>% arrange(desc(`Last Detection`))

# Manually remove receivers
tmp.receiverSummary <- tmp.receiverSummary %>% filter(Receiver != "Davies Point" & Receiver != "Corrie Island")
#tmp.receiverSummary$lon[7] = 151.6811

kable(tmp.receiverSummary, align = "l") %>% kableExtra::kable_styling()
```

```{r Receiver Summary - Specific Date Range}
# Note: not working
# Need to first save df.activity to file (so that it can be read here)
# in progress in "ExploreReceiverDatabase.Rmd"

print("Generating detection summary for each receiver")

start_date <- as.Date("2024-07-01")
#start_date <- as.Date("2023-03-20")

df.alltags.tmp <- df.alltags %>% filter(
  dateAus >= start_date
)

# Get list of receivers from the raw receiver summary.
# This is to include all receivers (find better way of doing this later)

#receiverList <- df.alltags.tmp$recvDeployName %>% unique()
receiverList <- receiverSummary$recvDeployName
receiverCount <- receiverList %>% length()

# Create empty data frame to use for the summary
tmp.receiverSummary <- as.data.frame(receiverList)
colnames(tmp.receiverSummary) <- c("recvDeployName")

for (i in 1:receiverCount) {
  # Get the first and most recent detections for each station.
  # Note: suppressWarnings is used for warning message regarding NA values (station with no detections)
  tmp.receiverSummary$recentDetection[i] <- df.alltags.tmp %>% filter(recvDeployName == receiverList[i]) %>% dplyr::select(ts) %>% max() %>% suppressWarnings()
  tmp.receiverSummary$firstDetection[i] <- df.alltags.tmp %>% filter(recvDeployName == receiverList[i]) %>% dplyr::select(ts) %>% min() %>% suppressWarnings()
}

# Convert detection times to Australian (Sydney) timezone
tmp.receiverSummary <- mutate(tmp.receiverSummary, 
                       recentDetectionAus = recentDetection %>% as_datetime(tz = "Australia/Sydney"),
                       firstDetectionAus = firstDetection %>% as_datetime(tz = "Australia/Sydney"))

# Remove columns with original integer time value
tmp.receiverSummary <- tmp.receiverSummary %>% dplyr::select(recvDeployName, firstDetectionAus, recentDetectionAus)

# Sort by most recent detection
tmp.receiverSummary <- tmp.receiverSummary %>% arrange(desc(recentDetectionAus))

# Count the number of unique tags detected by each station, and add to the data frame.
tmp.receiverSummary <- left_join(tmp.receiverSummary, df.alltags.tmp %>% 
                            count(recvDeployName,motusTagID) %>% 
                            count(recvDeployName) %>% 
                            rename("uniqueTags"="n"), by = "recvDeployName")

# Add list of species that the receiver has detected
tmp.receiverSummary <- cbind(tmp.receiverSummary, species = NA)
for (i in 1:nrow(tmp.receiverSummary)){
  tmp.receiverSummary$species[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(speciesEN) %>% unique() %>% list()
}

# Add list of tags that the receiver has detected
tmp.receiverSummary <- cbind(tmp.receiverSummary, motusTagID = NA)
for (i in 1:nrow(tmp.receiverSummary)){
  tmp.receiverSummary$motusTagID[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(motusTagID) %>% unique() %>% list()
}

# Adding lat and long
for (i in 1:receiverCount) {
  tmp.receiverSummary$lat[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(recvDeployLat) %>% unique()
  tmp.receiverSummary$lon[i] <- df.alltags.tmp %>% filter(recvDeployName == tmp.receiverSummary$recvDeployName[i]) %>% dplyr::select(recvDeployLon) %>% unique() 
}

# Add list of serno's and motus device IDs that have been deployed for the station name (recvDeployName)
for (i in 1:receiverCount){
  tmp.receiverSummary$sernos[i] <- df.recvDeps %>% 
    filter(stationName == tmp.receiverSummary$recvDeployName[i]) %>% 
    select(serno) %>% 
    unique()
  
  tmp.receiverSummary$deviceIDs[i] <- df.recvDeps %>% 
    filter(stationName == tmp.receiverSummary$recvDeployName[i]) %>% 
    select(deviceID) %>% 
    unique()
  
  tmp.receiverSummary$deployIDs[i] <- df.recvDeps %>% 
    filter(stationName == tmp.receiverSummary$recvDeployName[i]) %>% 
    select(deployID) %>% 
    unique()
}

# Add activity information
for (i in 1:receiverCount){
  df.activity.station <- activity_by_name(tmp.receiverSummary$recvDeployName[i]) %>% 
    filter(date >= start_date)
  # Most recent day with radio activity
  tmp.receiverSummary$recentActivity[i] <- as.Date(df.activity.station$date %>% max())
  
  # Number of days with activity since 1st July 2024
  tmp.receiverSummary$detectingDays[i] <- df.activity.station$date %>% 
    unique() %>% 
    length()
}

tmp.receiverSummary <- tmp.receiverSummary %>% 
  dplyr::select(recvDeployName, 
                firstDetectionAus, 
                recentDetectionAus, 
                uniqueTags, 
                species,
                recentActivity,
                detectingDays) %>% 
  mutate(firstDetectionAus = as.Date(firstDetectionAus), 
         recentDetectionAus = as.Date(recentDetectionAus),
         recentActivity = as.Date(recentActivity)) %>%  
  rename("Receiver" = "recvDeployName", 
         "First Detection" = "firstDetectionAus", 
         "Last Detection" = "recentDetectionAus", 
         "Unique Tags" = "uniqueTags",
         "Species" = "species") %>% arrange(desc(`Last Detection`))

# Manually remove receivers
tmp.receiverSummary <- tmp.receiverSummary %>% filter(Receiver != "Davies Point" & Receiver != "Corrie Island")
#tmp.receiverSummary$lon[7] = 151.6811

kable(tmp.receiverSummary, align = "l") %>% kableExtra::kable_styling()
```


```{r Species Summary}
speciesSummary %>% 
  as_tibble() %>% 
  mutate(motusTagIDs = map_chr(motusTagIDs, toString)) %>% 
  kable(align = "c") %>% 
  kable_styling()
```


```{r "StationDays" Summary}
# NOT WORKING
# Not sure where stationDaysProportion comes from - I think it was in occurrence_stats

tmp.stationDays <- stationDaysProportion %>% dplyr::select(recvDeployName, proportion) %>% arrange(desc(proportion)) %>% mutate(proportion = percent(proportion)) %>% rename("Receiver" = "recvDeployName", "Sum of Station Days" = "proportion")
# Manually add Hexham
tmp.stationDays[7,1] <- "Hexham Swamp"
tmp.stationDays[7,2] <- percent(0)
#tmp.stationDays <- tmp.stationDays %>% arrange(desc(`Sum of Station Days`))
kable(tmp.stationDays, align = "l") %>% kableExtra::kable_styling()
```

```{r Shapefile Receiver Summary}
# Check column types
print(receiverSummary %>% sapply(class))

receiverSummaryOut <- receiverSummary %>% mutate(
  species = sapply(species, paste, collapse = ", "),
  motusTagID = sapply(motusTagID, paste, collapse = ", "),
  lat = as.numeric(sapply(lat, function(x) if(length(x)==1) x[[1]] else NA)),
  lon = as.numeric(sapply(lon, function(x) if(length(x)==1) x[[1]] else NA))
)

print(receiverSummaryOut %>% sapply(class))
print(receiverSummaryOut %>% head())

sf_points <- st_as_sf(receiverSummaryOut, coords = c("lon", "lat"), crs = 4326, remove = FALSE)

output_shapefile_path <- "GIS Map/shorebird_stations.gpkg" # This will save in your current working directory

# Write the sf object to a shapefile
# delete_layer = TRUE will overwrite the shapefile if it already exists
st_write(sf_points, 
         dsn = output_shapefile_path, 
         layer = "shorebird_stations",
         driver = "GPKG",
         delete_layer = TRUE)
```

