---
title: "Map_Test"
author: "Callum Gapes"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Import tif File}
map.raster <- stack("data/StationMap.tif")

# Convert to dataframe and rename colour bands (RGB)
df <- map.raster %>% as.data.frame(xy = TRUE)
df <- df %>% rename(Red = StationMap_1,
                    Green = StationMap_2,
                    Blue = StationMap_3)
```

```{r}
ggplot(data = df, aes(x = x, y =y))+                   #plot map
  geom_raster(fill = rgb(r = Red,
                         g = Green,
                         b = Blue,
                         maxColorValue = 255),
                         show.legend = FALSE) +
  scale_fill_identity() + 
  ggtitle("Plot .tif rgb") +
  theme_minimal() -> Map
ggsave(Map,                                            #save map
      filename = "data/satellite_img.jpg",
      dpi = 200)
```

```{r Terra Package - Size = Number of Unique Detections}
# Import image
r <- rast("data/StationMap.tif")

# Plot in true colour
plotRGB(aggregate(r,10))

# Select information from receiver info
receiver.map <- receiverInfo %>% dplyr::select(recvDeployName, uniqueTags, lat, lon) %>% arrange (desc(uniqueTags))#%>% filter(is.na(uniqueTags) == FALSE) 

## TO FIX LATER - Download individual .motus files for each station so that the coordinates of stations with no detections can be included (without manual input)
# Manual coordinate input for now
receiver.map$lat[7] = -32.8467
receiver.map$lon[7] = 151.6811
receiver.map$lat[8] = -32.6906
receiver.map$lon[8] = 151.9698
receiver.map$lat[9] = -32.6843
receiver.map$lon[9] = 152.1371
  
# Get lat and long and convert to SpatVector (spatial vector from Terra package)
lat <- receiver.map %>% dplyr::select(lat) %>% lapply(as.numeric) %>% unlist()
lon <- receiver.map %>% dplyr::select(lon) %>% lapply(as.numeric) %>% unlist()
lonlat <- cbind(lon, lat)
receiver.points <- lonlat %>% vect(crs = "+proj=longlat +datum=WGS84") %>% project("EPSG:3857")

# Receiver names
receiver.points$name <- receiver.map$recvDeployName

# Extract number of unique tags to use as point size
receiver.points$uniqueTags <- receiver.map %>% dplyr::select(uniqueTags) %>% lapply(as.numeric) %>% unlist()

# Scale point sizes for display
pointSize.min <- 3
pointSize.max <- 9
receiver.points$pointSize <- receiver.points$uniqueTags %>% LinScale(newlow = pointSize.min, newhigh = pointSize.max)

# Manually set point size for NA values (no tag detections)
pointSize.empty <- 5
receiver.points$pointSize <- case_when(is.na(receiver.points$uniqueTags) ~ pointSize.empty, .default = receiver.points$pointSize)

# Set NA values to zero (for text labels and point type)
receiver.points$uniqueTags <- case_when(is.na(receiver.points$uniqueTags) ~ 0, .default = receiver.points$uniqueTags)

# Point type (empty circle for no detections)
pointType.detection <- 16
pointType.noDetection <- 1
receiver.points$pointType <- case_when(receiver.points$uniqueTags == 0 ~ pointType.noDetection, .default = pointType.detection)

# Add points to plot
points(receiver.points, cex = receiver.points$pointSize, pch = receiver.points$pointType, col = "yellow")

# Get origin / center
orig.x <- mean(c(ext(r)[1],ext(r)[2]))
orig.y <- mean(c(ext(r)[3],ext(r)[4]))

pos.below <- 1
pos.left <- 2
pos.above <- 3
pos.right <- 4

# Custom name label positions
receiver.points$pointPos <- c(pos.above, 
                              pos.below, 
                              pos.above, 
                              pos.right, 
                              pos.above, 
                              pos.below, 
                              pos.above, 
                              1, 
                              1)

# Offset depending on point size (didn't work for some reason)
# receiver.points$pointOffset <- LinScale(receiver.points$pointSize, newlow = 0.5, newhigh = 3)

# Add text labels to plot
text(receiver.points, labels = receiver.points$uniqueTags, halo = TRUE, cex = 1.2)
text(receiver.points, labels = receiver.points$name, halo = TRUE, cex = 1.2, pos = receiver.points$pointPos, offset = 2)
#textxy(geom(receiver.points, df = TRUE)$x, geom(receiver.points, df = TRUE)$y, labs = receiver.points$name, m = c(orig.x, orig.y), cex = 1, offset = 0.8, halo = TRUE)

# Add North arrow
# north.xOffset <- 21200
# north.yOffset <- 2000
# north.x <- ext(r)[1] + north.xOffset
# north.y <- ext(r)[3] + north.yOffset
# north(xy = c(north.x,north.y), type = 2, cex = 1.5)


# Add Scale Bar
# scale.xOffset <- 2000
# scale.yOffset <- 2000
# scale.x <- ext(r)[1] + scale.xOffset
# scale.y <- ext(r)[3] + scale.yOffset
# sbar(xy = c(scale.x, scale.y), divs = 4, type = "line", halo = TRUE, lwd = 4, ticks = TRUE, lonlat = FALSE, scaleby = 1000, labels = c(0,8,"4"))
# text(y = scale.y, x = (scale.x + 4000), labels = c("km"), cex = 3, halo = TRUE)

```

```{r Terra Package - Size = Proportion of StationDays}
# Import image
r <- rast("data/StationMap.tif")

# Plot in true colour
plotRGB(aggregate(r,10))

# Select information from receiver info
receiver.map <- receiverInfo %>% dplyr::select(recvDeployName, uniqueTags, lat, lon) %>% arrange(desc(uniqueTags))#%>% filter(is.na(uniqueTags) == FALSE)

## TO FIX LATER - Download individual .motus files for each station so that the coordinates of stations with no detections can be included (without manual input)
# Manual coordinate input for now
receiver.map$lat[7] = -32.8467
receiver.map$lon[7] = 151.6811
receiver.map$lat[8] = -32.6906
receiver.map$lon[8] = 151.9698
receiver.map$lat[9] = -32.6843
receiver.map$lon[9] = 152.1371
  
# Get lat and long and convert to SpatVector (spatial vector from Terra package)
lat <- receiver.map %>% dplyr::select(lat) %>% lapply(as.numeric) %>% unlist()
lon <- receiver.map %>% dplyr::select(lon) %>% lapply(as.numeric) %>% unlist()
lonlat <- cbind(lon, lat)
receiver.points <- lonlat %>% vect(crs = "+proj=longlat +datum=WGS84") %>% project("EPSG:3857")

# Receiver names
receiver.points$name <- receiver.map$recvDeployName

# Proportion of stationDays
for (i in 1:nrow(receiver.points)){
  if (length(filter(stationDaysProportion, recvDeployName == receiver.points$name[i])$proportion)!= 0){
  receiver.points$stationDays[i] <- filter(stationDaysProportion, recvDeployName == receiver.points$name[i])$proportion
  }
  else {
    receiver.points$stationDays[i] <- NA
  }
}

receiver.points$stationDays <- receiver.points$stationDays %>% as.numeric()

# Extract number of unique tags to use as point size
#receiver.points$uniqueTags <- receiver.map %>% dplyr::select(uniqueTags) %>% lapply(as.numeric) %>% unlist()

# Scale point sizes for display
pointSize.min <- 3
pointSize.max <- 9
receiver.points$pointSize <- receiver.points$stationDays %>% LinScale(newlow = pointSize.min, newhigh = pointSize.max)

# Manually set point size for NA values (no tag detections)
pointSize.empty <- 5
receiver.points$pointSize <- case_when(is.na(receiver.points$stationDays) ~ pointSize.empty, .default = receiver.points$pointSize)

# Set NA values to zero (for text labels and point type)
receiver.points$stationDays <- case_when(is.na(receiver.points$stationDays) ~ 0, .default = receiver.points$stationDays)

# Point type (empty circle for no detections)
pointType.detection <- 16
pointType.noDetection <- 1
receiver.points$pointType <- case_when(receiver.points$stationDays == 0 ~ pointType.noDetection, .default = pointType.detection)

# Add points to plot
points(receiver.points, cex = receiver.points$pointSize, pch = receiver.points$pointType, col = "yellow")

# Get origin / center
orig.x <- mean(c(ext(r)[1],ext(r)[2]))
orig.y <- mean(c(ext(r)[3],ext(r)[4]))

pos.below <- 1
pos.left <- 2
pos.above <- 3
pos.right <- 4

# Custom name label positions
receiver.points$pointPos <- c(pos.above, 
                              pos.below, 
                              pos.above, 
                              pos.right, 
                              pos.above, 
                              pos.below, 
                              pos.above, 
                              1, 
                              1)

# Offset depending on point size (didn't work for some reason)
# receiver.points$pointOffset <- LinScale(receiver.points$pointSize, newlow = 0.5, newhigh = 3)

# Add text labels to plot
text(receiver.points, labels = percent(receiver.points$stationDays, accuracy = 1), halo = TRUE, cex = 1.2)
text(receiver.points, labels = receiver.points$name, halo = TRUE, cex = 1.2, pos = receiver.points$pointPos, offset = 2)


```

```{r Terra Package - Unique Species}
# Import image
r <- rast("data/StationMap.tif")

# Plot in true colour
plotRGB(aggregate(r,10))

# Select information from receiver info
receiver.map <- receiverInfo %>% dplyr::select(recvDeployName, uniqueTags, lat, lon, species) %>% arrange(desc(uniqueTags)) #%>% filter(is.na(uniqueTags) == FALSE)

## TO FIX LATER - Download individual .motus files for each station so that the coordinates of stations with no detections can be included (without manual input)
# Manual coordinate input for now
receiver.map$lat[7] = -32.8467
receiver.map$lon[7] = 151.6811
receiver.map$lat[8] = -32.6906
receiver.map$lon[8] = 151.9698
receiver.map$lat[9] = -32.6843
receiver.map$lon[9] = 152.1371
  
# Get lat and long and convert to SpatVector (spatial vector from Terra package)
lat <- receiver.map %>% dplyr::select(lat) %>% lapply(as.numeric) %>% unlist()
lon <- receiver.map %>% dplyr::select(lon) %>% lapply(as.numeric) %>% unlist()
lonlat <- cbind(lon, lat)
receiver.points <- lonlat %>% vect(crs = "+proj=longlat +datum=WGS84") %>% project("EPSG:3857")

# Receiver names
receiver.points$name <- receiver.map$recvDeployName

# Proportion of stationDays
for (i in 1:nrow(receiver.points)){
  if (length(filter(stationDaysProportion, recvDeployName == receiver.points$name[i])$proportion)!= 0){
  receiver.points$stationDays[i] <- filter(stationDaysProportion, recvDeployName == receiver.points$name[i])$proportion
  }
  else {
    receiver.points$stationDays[i] <- NA
  }
}

receiver.points$stationDays <- receiver.points$stationDays %>% as.numeric()

# Extract number of unique tags to use as point size
#receiver.points$uniqueTags <- receiver.map %>% dplyr::select(uniqueTags) %>% lapply(as.numeric) %>% unlist()

# Scale point sizes for display
pointSize.min <- 3
pointSize.max <- 9
receiver.points$pointSize <- receiver.points$stationDays %>% LinScale(newlow = pointSize.min, newhigh = pointSize.max)

# Manually set point size for NA values (no tag detections)
pointSize.empty <- 5
receiver.points$pointSize <- case_when(is.na(receiver.points$stationDays) ~ pointSize.empty, .default = receiver.points$pointSize)

# Set NA values to zero (for text labels and point type)
receiver.points$stationDays <- case_when(is.na(receiver.points$stationDays) ~ 0, .default = receiver.points$stationDays)

# Point type (empty circle for no detections)
pointType.detection <- 16
pointType.noDetection <- 1
receiver.points$pointType <- case_when(receiver.points$stationDays == 0 ~ pointType.noDetection, .default = pointType.detection)

# Add points to plot
points(receiver.points, cex = 2, col = "yellow")

# Get origin / center
orig.x <- mean(c(ext(r)[1],ext(r)[2]))
orig.y <- mean(c(ext(r)[3],ext(r)[4]))

pos.below <- 1
pos.left <- 2
pos.above <- 3
pos.right <- 4

# Custom name label positions
receiver.points$pointPos <- c(pos.above, 
                              pos.below, 
                              pos.above, 
                              pos.left, 
                              pos.above, 
                              pos.below, 
                              pos.above, 
                              1, 
                              1)

receiver.points$speciesPos <- c(pos.above, 
                              pos.below, 
                              pos.above, 
                              4, 
                              pos.above, 
                              pos.below, 
                              3, 
                              1, 
                              1)


# Offset depending on point size (didn't work for some reason)
# receiver.points$pointOffset <- LinScale(receiver.points$pointSize, newlow = 0.5, newhigh = 3)

#receiver.map <- mutate(receiver.map, speciesText = species %>% unlist() %>% paste0(collapse = "\n"))
for (i in 1:nrow(receiver.map)){
  receiver.map$speciesText[i] <- receiver.map$species[i] %>% unlist() %>% paste(collapse = "\n")
}

# Add text labels to plot
#text(receiver.points, labels = percent(receiver.points$stationDays, accuracy = 1), halo = TRUE, cex = 1.2)
text(receiver.points, labels = receiver.map$speciesText, halo = TRUE, cex = 0.8, pos = receiver.points$speciesPos, offset = 2)
text(receiver.points, labels = receiver.points$name, halo = TRUE, cex = 1.2, pos = receiver.points$pointPos, offset = 0.5)


```



