---
title: "Occurrence_Stats"
author: "Callum Gapes"
date: "2023-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/callu/Documents/Shorebird Monitoring NSW")

# ---- Load packages ----
library(dplyr)
library(forcats)
library(ggplot2)
library(rstatix)
library(viridis)

# ---- Load custom functions and variables
source("R Files/shorebirdFunctions.R")
source("R Files/plotDefaults.R")

df.alltags <- readRDS("Data/df.alltags.rds")
tagSummary <- readRDS("Data/tagSummary.rds")

```

# ==== Occurrence Stats  ====
```{r Occurrence by Station and Tidal Category}
## Occurrence = (num days tag detected at station during tidal category)/(num days tag detected at station)

## How many days was each tag detected in each tidal category at each station?
occurrenceStation <- df.alltags %>% count(dateAus, motusTagID, tideCategory, recvDeployName) %>% 
  count(tideCategory, motusTagID, recvDeployName) %>% 
  rename("days"="n") %>% 
  # Include zero values
  complete(tideCategory, nesting(motusTagID, recvDeployName), fill = list(days = 0))

## Find total number of days that each tag was detected at each station
stationDetections <- df.alltags %>% count(dateAus, motusTagID, recvDeployName) %>% count(motusTagID, recvDeployName) %>% rename("stationDays"="n")
stationDetections$motusTagID <- stationDetections$motusTagID %>% as.factor()

## Add number of station detections to occurrenceStation data frame
occurrenceStation <- left_join(occurrenceStation, dplyr::select(stationDetections,stationDays,motusTagID,recvDeployName),by=c("motusTagID","recvDeployName"))

## Add species from tagSummary
occurrenceStation <- left_join(occurrenceStation, dplyr::select(tagSummary,speciesEN,motusTagID),by="motusTagID")

## Proportion of detection days that each tag was detected in each tidal category
occurrenceStation <- occurrenceStation %>% mutate(proportion = days/stationDays)

## Custom factor order for plot
occurrenceStation <- occurrenceStation %>% mutate(tideCategory = fct_relevel(tideCategory,"Falling","Low","Rising","High"))

stationDaysProportion <- occurrenceStation %>% group_by(recvDeployName) %>% summarise(total = sum(stationDays)) %>% mutate(proportion = total/sum(total))
```

```{r Single Species Plot}
#species.tmp <- "Pied Stilt"
#species.tmp <- "Red-necked Avocet"
species.tmp <- "Bar-tailed Godwit"
occurrence.tmp <- occurrenceStation %>% filter(speciesEN == species.tmp)

## Jitter
p <- occurrence.tmp %>% ggplot(aes(x=tideCategory,y=proportion,color = motusTagID)) + 
  geom_jitter(position=position_jitter(0.1), size = 2) +
  #stat_summary(fun.y = mean, geom = "point", shape = 18, size = 5,aes(color = tideCategory)) +
  facet_grid(vars(recvDeployName)) + 
  ggtitle(paste("Occurrence for Tidal Categories for",species.tmp)) + theme(plot.title = element_text(hjust = 0.5))
p

## Boxplot
p <- occurrence.tmp %>% ggplot(aes(x=tideCategory,y=proportion,fill = tideCategory)) + 
  geom_boxplot(alpha = 0.7) +
  #stat_summary(fun.y = mean, geom = "point", shape = 18, size = 5,aes(color = tideCategory)) +
  facet_grid(vars(recvDeployName)) + 
  ggtitle(paste("Occurrence for Tidal Categories for",species.tmp)) + theme(plot.title = element_text(hjust = 0.5))
p

## Summary values
occurrence.tmp.summary <- occurrence.tmp %>% group_by(tideCategory, recvDeployName) %>% 
  summarise(
    proportionMean = mean(proportion),
    sd = sd(proportion),
    n = n(),
    se = sd/sqrt(n)
  )

# Only include values with at least 3 individuals
occurrence.tmp.summary <- occurrence.tmp.summary %>% filter(n > 2)

# Barplot with standard error
p <- occurrence.tmp.summary %>% ggplot( aes(x = tideCategory, y = proportionMean, fill = recvDeployName)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin = proportionMean - se, ymax = proportionMean + se), width = .2, position = position_dodge(0.9)) +
  #geom_errorbar(data = predictions, aes(x = tideCategory, ymin = lwr, ymax = upr), width = 0.2, position = position_dodge(0.9)) +
  labs(
    x = "Tide Category",
    y = "Mean Occurrence",
    title = paste("Occurrence by Tidal Category for ",species.tmp)
  ) +
  theme_gray(base_size = 16) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = "Receiver")
  #theme_minimal()
p
```

```{r ANOVA}
species.tmp <- "Pacific Golden-Plover"
#receiver.tmp <- "Barry_Fullerton_cove"
receiver.tmp <- "Hexham Swamp"
modelData <- occurrenceStation %>% filter(recvDeployName == receiver.tmp & speciesEN == species.tmp)

aov.res <- aov(proportion ~ tideCategory ,data = modelData)
aov.res %>% summary()

shapiro.test(aov.res$residuals)
```

```{r Friedman Test}
#species.tmp <- "Red-necked Avocet"
species.tmp <- "Bar-tailed Godwit"
#receiver.tmp <- "Barry_Fullerton_cove"
#receiver.tmp <- "Curlew Point"
#receiver.tmp <- "Tomago"
modelData <- occurrenceStation %>% filter(recvDeployName == receiver.tmp & speciesEN == species.tmp)
modelData$motusTagID = factor(modelData$motusTagID, levels = unique(modelData$motusTagID))
modelData$tideCategory = factor(modelData$tideCategory, levels = unique(modelData$tideCategory))

res.aov <- modelData %>% anova_test(dv = proportion, wid = motusTagID, within = tideCategory)
res.aov

res.fried <- modelData %>% friedman_test(proportion ~ tideCategory | motusTagID)
res.fried
modelData %>% friedman_effsize(proportion ~ tideCategory | motusTagID)

```



```{r Andrea Linear Model Test}
species.tmp <- "Pacific Golden-Plover"
receiver.tmp <- "Hexham Swamp"

modelData <- occurrenceStation %>% filter(recvDeployName == receiver.tmp & speciesEN == species.tmp)

# Fit a linear model
model <- lm(proportion ~ tideCategory, modelData)
 
# Create a new data frame for prediction
new_data <- data.frame(tideCategory <- levels(modelData$tideCategory))
 
# Make predictions using the linear model
predictions <- predict(model, newdata = new_data, interval = "confidence") %>% as.data.frame()
 
# Create a plot
ggplot() +
  geom_bar(data = modelData, aes(x = tideCategory, y = proportion), stat = "summary", fun = "mean", fill = "blue") +
  geom_errorbar(data = predictions, aes(x = tideCategory, ymin = lwr, ymax = upr), width = 0.2, position = position_dodge(0.9)) +
  labs(
    x = "Tide Category",
    y = "Fitted Mean Proportion",
    title = "Fitted Means with Confidence Intervals by Tide Category"
  ) +
  theme_minimal()
```

```{r Plot of Occurrence, With All Species}
# Jitter plot, facet by receiver
p <- occurrenceStation %>% ggplot(aes(x=tideCategory,y=proportion,color = tideCategory)) + 
  geom_jitter(position=position_jitter(0.1)) +
  stat_summary(fun = mean, geom = "point", shape = 18, size = 5,aes(color = tideCategory)) +
  facet_grid(vars(recvDeployName))
p
```

```{r Single Receiver Plot}
## Select receiver
receiver.tmp <- "Fullerton Entrance"

## Filter occurrence by receiver
tmpOccurrence <- occurrenceStation %>% filter(recvDeployName == receiver.tmp)

# Jitter plot, facet by species
p <- tmpOccurrence %>% ggplot(aes(x=tideCategory,y=proportion,color = tideCategory)) + 
  geom_jitter(position=position_jitter(0.1)) +
  stat_summary(fun.y = mean, geom = "point", shape = 18, size = 5,aes(color = tideCategory)) +
  facet_grid(vars(speciesEN)) +
  ggtitle(paste("Occurrence for",receiver.tmp,"- By Species")) + theme(plot.title = element_text(hjust = 0.5))
p
```

```{r All-Single-Receiver-Plots}
for (i in 1:nrow(occurrenceStation %>% select(recvDeployName) %>% unique())) {
  tmpReceiver <- (occurrenceStation %>% select(recvDeployName) %>% unique())$recvDeployName[i]
  
  ## Filter occurrence by receiver
  tmpOccurrence <- occurrenceStation %>% filter(recvDeployName == tmpReceiver)

# Jitter plot
p <- tmpOccurrence %>% ggplot(aes(x=tideCategory,y=proportion,color = tideCategory)) + 
  geom_jitter(position=position_jitter(0.1)) +
  stat_summary(fun.y = mean, geom = "point", shape = 18, size = 9,aes(color = tideCategory)) +
  ggtitle(paste("Occurrence for",tmpReceiver,"- All Tags")) + theme(plot.title = element_text(hjust = 0.5))
p

save.plot()

# Jitter plot, facet by species
p <- tmpOccurrence %>% ggplot(aes(x=tideCategory,y=proportion,color = tideCategory)) + 
  geom_jitter(position=position_jitter(0.1)) +
  stat_summary(fun.y = mean, geom = "point", shape = 18, size = 5,aes(color = tideCategory)) +
  facet_grid(vars(speciesEN)) +
  ggtitle(paste("Occurrence for",tmpReceiver,"- By Species")) + theme(plot.title = element_text(hjust = 0.5))
p

save.plot()

rm(tmpOccurrence)
}

```

```{r Species-By-Station Plots}
for (i in 1:nrow(occurrenceStation %>% select(speciesEN) %>% unique())) {
  tmpSpecies <- unique(select(occurrenceStation,speciesEN))$speciesEN[i]
  tmpOccurrence <- occurrenceStation %>% filter(speciesEN == tmpSpecies)
  
  # Jitter plot, facet by receiver
p <- tmpOccurrence %>% ggplot(aes(x=tideCategory,y=proportion,colour = as.factor(motusTagID))) + 
  geom_jitter(position=position_jitter(0), size = 3)
  
  if (tmpOccurrence %>% select(motusTagID) %>% unique() %>% count() > 1) {
  # Add mean (if more than 1 individual)
  p <- p + stat_summary(fun = "mean", geom = "point", shape = 4, size = 3, colour = "black",mapping = aes(group = tideCategory), show.legend = FALSE)
    }
  
  # Facet by receiver
  p <- p + facet_grid(vars(recvDeployName)) + 
  
  # Title
  ggtitle(paste("Occurrence for Tidal Categories for",tmpSpecies)) + theme(plot.title = element_text(hjust = 0.5)) + 
  
  # Legend name
  labs(colour = "Motus Tag ID")

p

save.plot()
rm(tmpOccurrence)
}

```


# ==== Old / unused code ====

```{r Test - Add Zero Values}
# Change variables to factors
df.alltags_factor <- df.alltags %>% mutate_at(vars(dateAus, motusTagID, tideCategory, recvDeployName),list(factor))

tmp1 <- df.alltags_factor %>% select(dateAus, motusTagID, tideCategory, recvDeployName)

tmp2 <- tmp1 %>% unique()

tmp3 <- tmp2 %>% count(tideCategory,motusTagID, recvDeployName) %>% rename("days" = "n")

tmp4 <- tmp3 %>% complete(tideCategory, nesting(motusTagID, recvDeployName), fill = list(days = 0))

## Add number of station detections to occurrenceStation data frame
occurrenceStation <- left_join(tmp4, select(stationDetections,stationDays,motusTagID,recvDeployName),by=c("motusTagID","recvDeployName"))

## Add species from tagSummary
tagSummary$motusTagID <- as.factor(tagSummary$motusTagID)
occurrenceStation <- left_join(occurrenceStation, select(tagSummary,speciesEN,motusTagID),by="motusTagID")

## Proportion of detection days that each tag was detected in each tidal category
occurrenceStation <- occurrenceStation %>% mutate(proportion = days/stationDays)

## Custom factor order for plot
occurrenceStation <- occurrenceStation %>% mutate(tideCategory = fct_relevel(tideCategory,"Falling","Low","Rising","High"))
```

```{r All-Tag-Occurrence-No-Station}
## On how many days has each tag been detected?
df.alltags %>% count(dateAus,motusTagID) %>% count(motusTagID)

## What proportion of days (between first and last detection) was each tag detected?
tagSummary <- mutate(tagSummary, detectionProportion = detectionDays/numDays)

## How many days was each tag detected in each tidal category?
occurrenceNoStation <- df.alltags %>% count(dateAus, motusTagID, tideCategory) %>% count(tideCategory, motusTagID) %>% rename("days"="n")

## Add detectionDays and species from tagSummary
occurrenceNoStation <- left_join(occurrenceNoStation, select(tagSummary,speciesEN,detectionDays,motusTagID),by="motusTagID")

## Proportion of detection days that each tag was detected in each tidal category
occurrenceNoStation <- occurrenceNoStation %>% mutate(proportion = days/detectionDays)

## Custom factor order for plot
occurrenceNoStation <- occurrenceNoStation %>% mutate(tideCategory = fct_relevel(tideCategory,"Falling","Low","Rising","High"))

# Boxplot, with individual tag as the repeated unit
p <- occurrenceNoStation %>% ggplot(aes(tideCategory, proportion, fill = tideCategory)) + 
  geom_boxplot(alpha = 0.7) +
  ggtitle(paste("Detection Proportion of",tmpSpecies,"Species at")) + theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
  scale_fill_viridis(discrete = TRUE) 
p

# Jitter plot
p <- occurrenceNoStation %>% ggplot(aes(x=tideCategory,y=proportion,color = as.factor(motusTagID))) + 
  geom_jitter(position=position_jitter(0), size = 5) +
  #stat_summary(fun.y = mean, geom = "point", shape = 18, size = 12,aes(color = tideCategory)) +
  ggtitle("Occurrence for Tidal Categories - All Tags") + theme(plot.title = element_text(hjust = 0.5)) + labs(colour = "Motus Tag ID")
p

save.plot()

# Jitter plot, facet by species
p <- occurrenceNoStation %>% ggplot(aes(x=tideCategory,y=proportion,color = tideCategory)) + 
  geom_jitter(position=position_jitter(0.1)) +
  stat_summary(fun.y = mean, geom = "point", shape = 18, size = 5,aes(color = tideCategory)) +
  facet_grid(vars(speciesEN)) +
  ggtitle("Occurrence for Tidal Categories - By Species") + theme(plot.title = element_text(hjust = 0.5))
p

save.plot()


```

## Occurrence by Day by Tag by Tidal Category (Single species / station)
```{r Occurrence-Day-Tag-Tide}
dateStart <- ymd("2023-08-29",tz="Australia/Sydney")
dateEnd <- ymd("2023-09-20",tz="Australia/Sydney")
tmpSpecies <- "Pied Stilt"
tmpStation <- "Fullerton Entrance"
tmpTag <- "All"

# Filter by date range
tmp <- filter(df.alltags,dateAus >= dateStart, dateAus <= dateEnd)
# Calculate length of date range
numDays <- as.integer(dateEnd - dateStart + 1)

# Filter by species
if(tmpSpecies != "All"){
  tmp <- filter(tmp, speciesEN == tmpSpecies)
}

# Filter by station
if (tmpStation != "All"){
  tmp <- filter(tmp, recvDeployName == tmpStation)
}

# Filter by tag
if (tmpTag != "All"){
  tmp <- filter(tmp, motusTagID == tmpTag)
}

rm(occurrenceDaysTide)

# Presence: Number of days detected during tidal category 
occurrenceDaysTide <- tmp %>%
  count(dateAus,motusTagID,tideCategory) %>%
  count(motusTagID,tideCategory) %>%
  rename("days"="n") %>% 
  mutate(occurrence = days/numDays)

# Summarise by tideCategory
occurrenceDaysTide %>% 
  group_by(tideCategory) %>% 
  summarise(birdDays = sum(days),avgOccurrence = mean(occurrence))

# Boxplot, with individual tag as the repeated unit
p <- occurrenceDaysTide %>% ggplot(aes(tideCategory, days, fill = tideCategory)) + 
  geom_boxplot(alpha = 0.7) +
  ggtitle(paste("Detection Days of",tmpSpecies,"Species at",tmpStation,"Station")) + theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
  scale_fill_viridis(discrete = TRUE) +
  labs(subtitle = paste("From",dateStart,"-",dateEnd))
p

```

## Occurrence by Day by Tag
```{r Occurrence-Day-Tag}
dateStart <- ymd("2023-08-29",tz="Australia/Sydney")
dateEnd <- ymd("2023-09-20",tz="Australia/Sydney")
numDays <- as.integer(dateEnd - dateStart + 1)

occurrenceDaysTag <- filter(df.alltags,dateAus >= dateStart, dateAus <= dateEnd) %>% 
  count(dateAus,motusTagID) %>%
  count(motusTagID) %>%
  rename("days"="n") %>% 
  mutate(occurrence = days/numDays)
```
## Occurrence by Day by Species
```{r Occurrence-Day-Species}
dateStart <- ymd("2023-01-01",tz="Australia/Sydney")
dateEnd <- ymd("2023-05-05",tz="Australia/Sydney")
numDays <- as.integer(dateEnd - dateStart + 1)

occurrenceDaysSpecies <- filter(df.alltags,dateAus >= dateStart, dateAus <= dateEnd) %>% 
  count(dateAus,speciesEN) %>%
  count(speciesEN) %>%
  rename("days"="n") %>% 
  mutate(occurrence = days/numDays)
```