---
title: "Stilt Paper"
author: "Callum Gapes"
date: "2025-02-26"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup}
setwd("C:/Users/callu/Documents/Shorebird Monitoring NSW")
knitr::opts_knit$set(root.dir = "C:/Users/callu/Documents/Shorebird Monitoring NSW")

# ---- Load Packages ----
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(ggeasy)
library(purrr)
library(DT)
library(units)
library(lubridate)

# ---- Load Custom Functions ----
source("R Files/shorebirdFunctions.R")

# ---- Load Data ----
df.alltags <- readRDS("Data/df.alltags.rds")
tagSummary <- readRDS("Data/tagSummary.rds")
receiverSummary <- readRDS("Data/receiverSummary.rds")
tidalCurve <- readRDS("Data/tidalCurve.rds")
tideData <- readRDS("Data/tideData.rds")

# ---- DataTable Default Options ----
js_code_formatter <- "
function(data, type, row, meta) {
  if (type === 'display' && typeof data === 'number') {
    // Check if the number is an integer
    if (Number.isInteger(data)) {
      return data.toString(); // If integer, display as is (converted to string)
    } else {
      // If float, format to 2 decimal places
      return data.toFixed(2); 
    }
  }
  // Return original data for non-numeric types or non-display types
  return data; 
}"

options(DT.options = list(
  pageLength = 100,
  columnDefs = list(
    list(
      targets = '_all',
      render = DT::JS(js_code_formatter) # Pass the single string variable
    )
  )
  # , pageLength = 10 # Example
))

summ.species %>% datatable(filter = "top")
```

# ==== Detection Duration by Tide Period ====

```{r Calculate Detection Duration Per Tide Period}
# Set Time Bin Width
## We are interested in detections within 3 hours of a high / low tide.
## Set maximum time from the most recent high or low tide. Value is in hours.
## Note that this is either side of the tide, so bin width will be double.
tideTimeCutoff <- 3

# FILTER OUT ANY DETECTIONS FURTHER THAN 3 HOURS FROM HIGH / LOW TIDE
## Note that this prevents analysis of those other detections.
## They will need to be considered separately or the tidal classification
## code / data will have to be re-structured.
df.detections <- df.alltags %>% 
  filter(tideTimeDiff <= tideTimeCutoff)

df.byTidePeriod <- df.detections %>% 
  # Count the number of detections for each combination of unique tidal period,
  # receiver, and tag.
  group_by(motusTagID, recvDeployName, tideID) %>% 
  summarise(detectionCount = n(), .groups = "drop") %>% 
  # Add variables of interest from original data frame to the summarised result
  left_join(df.alltags %>% 
              select(motusTagID, 
                     recvDeployName, 
                     tideID, 
                     speciesEN, 
                     tideCategory, 
                     tagBI,
                     tideHighLow,
                     tideDiel) %>%
              distinct(), 
            by = c("motusTagID", "recvDeployName", "tideID")) %>%
  # Calculate detection duration by multiplying the number of detections and
  # the burst interval. detectionDuration is in seconds.
  mutate(detectionDuration = set_units(detectionCount*tagBI, "seconds"),
         #detectionDurationMin = detectionDuration/60) %>%
         detectionDurationMin = set_units(detectionDuration, "minutes")) %>% 
  mutate(tideCategory = fct_relevel(tideCategory, "Diurnal_Low", "Nocturnal_Low", "Diurnal_High", "Nocturnal_High"))

## Calculate detection duration in seconds
# df.byTidePeriod <- df.byTidePeriod %>% 
#   mutate(detectionDuration = detectionCount*tagBI,
#          detectionDurationMin = detectionDuration/60)


## Reorder factor levels for tideCategory to choose order in plot
df.byTidePeriod <- df.byTidePeriod %>%
  mutate(tideCategory = fct_relevel(tideCategory, "Diurnal_Low", "Nocturnal_Low", "Diurnal_High", "Nocturnal_High"))
```


```{r Complete Tide Period Summary - Add No-Detection Periods}
# So basically, need a unique list of valid tide periods for each tag.
# Already have list of tags with first and last detection in tagSummary
# Want to filter tideData for each combination
valid_tides <- tagSummary %>% mutate(
  valid_tide_periods = pmap(.l = list(firstDetectionAus, recentDetectionAus), .f = function(start, end){
    tideData %>% 
      filter(tideDateTimeAus >= start & tideDateTimeAus <= end) %>% 
      pull(tideID)
  })
) %>% unnest(valid_tide_periods) %>% 
  select(motusTagID, firstDetectionAus, recentDetectionAus, speciesEN, valid_tide_periods) %>% 
  rename(tideID = valid_tide_periods)

# Now want to expand for each receiver
## Note: all receivers will be included, validity based on whether the station was actually up / receiving at the time will be implemented later

valid_tides_stations <- valid_tides %>%
  complete(nesting(motusTagID, tideID)) %>% 
  crossing(recvDeployName = receiverSummary %>% pull(recvDeployName))
  

# Use left_join to add data for tidal periods WITH detections
#join.test <- valid_tides_stations %>% 
#  left_join(df.byTidePeriod, by = c("motusTagID","recvDeployName","tideID"))

tideData_renamed <- tideData %>% rename(
  tideHighLow = high_low,
  tideDiel = day_night
)

tideData_renamed <- tideData_renamed %>% 
  mutate(tideCategoryStart = tideDateTimeAus - 3600*3,
         tideCategoryEnd = tideDateTimeAus + 3600*3)


# Add tideCategory back to data frame (variable needed for summarising)
valid_tides_stations <- valid_tides_stations %>% 
  left_join(tideData_renamed %>% select(tideCategory, tideID, tideHighLow, tideDiel))

# Add data from tidal periods that have detections to the complete dataframe
df.allTidePeriods <- valid_tides_stations %>% 
  left_join(df.byTidePeriod,
            by = c("motusTagID", "tideID", "recvDeployName", "tideCategory", "speciesEN", "tideHighLow", "tideDiel")) %>% 
  select(motusTagID, tideID, recvDeployName, speciesEN, tideCategory, detectionDuration, tideHighLow, tideDiel)

# Add zeros 
df.allTidePeriods <- df.allTidePeriods %>% mutate(
  detectionDuration = replace_na(detectionDuration, set_units(0,"seconds"))
)

df.allTidePeriods <- df.allTidePeriods %>% mutate(
  detectionDuration = set_units(detectionDuration, "seconds")
)

### CODE VALIDATING STATION UPTIME NEEDS TO GO HERE ### 

# ==== SUMMARISE BY SPECIES AND TAG ====
# Now we can summarise back down to the level we are interested in
summ.tag <- df.allTidePeriods %>% 
  group_by(motusTagID, recvDeployName, tideCategory, speciesEN, tideHighLow, tideDiel) %>% 
  summarise(mean_duration = mean(detectionDuration),
            sd_duration = set_units(sd(detectionDuration),"seconds"),
            se_duration = set_units((sd(detectionDuration))/(sqrt(n())),"seconds"),
            #sd_duration = sd(detectionDuration),
            #se_duration = (sd(detectionDuration))/(sqrt(n())),
    #         sd_duration = if_else(n() > 1, 
    #                       sd(detectionDuration), 
    #                       set_units(0, "s")), # Must return a units object
    #                       
    # se_duration = if_else(n() > 1, 
    #                       sd(detectionDuration) / sqrt(n()), 
    #                       set_units(0, "s")),
            period_count = n(),
            period_detected_count = sum(detectionDuration > set_units(0, "seconds")),
            .groups = "drop")

# Further summarise to the species level
summ.species <- summ.tag %>%
  group_by(speciesEN, recvDeployName, tideCategory, tideHighLow, tideDiel) %>%
  summarise(mean_species = mean(mean_duration),
            sd_species = set_units(sd(mean_duration),"seconds"),
            se_species = set_units((sd_species)/(sqrt(n())),"seconds"),
            n_individual = n(),
            .groups = "drop")

summ.species %>% datatable(filter = "top")

# Set tideDiel and tideHighLow to factors with specific ordering
## Note this controls order displayed on the plots
summ.species <- summ.species %>% 
  mutate(
        tideDiel = factor(tideDiel, levels = c("Diurnal", "Nocturnal")),
        tideHighLow = factor(tideHighLow, levels = c("Low", "High"))) 

# Arrange by species / tideCategory group with greatest mean detection time
summ.species <- summ.species %>% 
  group_by(speciesEN, recvDeployName) %>% 
  mutate(group_max_mean = max(mean_species)) %>% 
  ungroup() %>% 
  arrange(desc(group_max_mean), tideHighLow, tideDiel)

summ.species %>% datatable(filter = "top")

# Attempt to save filtered datatable to a html file
dtable <- summ.species %>% datatable(filter = "top")
html <- "Tables/MeanDetection_BySpecies.html"

saveWidget(dtable, html)

## Also save as a csv (for emailing)
write.xlsx(summ.species, "Tables/MeanDetection_BySpecies.xlsx")

# Filter to the max value for each combination of species / receiver
summ.species_clean <- summ.species %>% group_by(speciesEN, recvDeployName) %>% filter(mean_species == max(mean_species)) %>% select(-c(tideHighLow, tideDiel, group_max_mean)) %>% ungroup()
write.xlsx(summ.species_clean, "Tables/MeanDetection_BySpecies_Clean.xlsx")
```

## ---- Plots - All Tide Periods ----

```{r Single Species Plot - INCLUDING NO-DETECTION PERIODS}
# Select species of interest
#tmp.species <- "Pacific Golden-Plover"
tmp.species <- "Red-necked Avocet"
#tmp.species <- "Pied Stilt"

errorBarLabelOffset = set_units(0.1, "seconds")

summ.species_individual <- summ.species %>% 
  filter(speciesEN == tmp.species)

# Create the bar plot with error bars
ggplot(summ.species_individual, aes(x = recvDeployName, y = mean_species, fill = tideCategory)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), colour = "black") + 
  geom_errorbar(aes(ymin = mean_species - se_species, ymax = mean_species + se_species),
                position = position_dodge(width = 0.9), width = 0.2) +
  geom_text(aes(label = paste0("n=", n_individual), 
                y = mean_species + se_species + errorBarLabelOffset), 
            position = position_dodge(width = 0.9), vjust = -0.5) + 
  theme_minimal() +
  labs(
    title = paste(sep =" ", "Mean Detection Duration for Species",tmp.species),
    x = "Site",
    y = "Mean Detection Duration",
    fill = "Tide Category"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  easy_center_title()
```
```{r Single Species Single Station Plot - INCLUDING NO-DETECTION PERIODS}
# Select species of interest
#tmp.species <- "Pacific Golden-Plover"
tmp.species <- "Red-necked Avocet"
#tmp.species <- "Pied Stilt"

tmp.receiver <- "Curlew Point"

errorBarLabelOffset = set_units(0.1, "seconds")

summ.species_individual <- summ.species %>% 
  filter(speciesEN == tmp.species,
         recvDeployName == tmp.receiver)

# Create the bar plot with error bars
ggplot(summ.species_individual, aes(x = recvDeployName, y = mean_species, fill = tideCategory)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), colour = "black") + 
  geom_errorbar(aes(ymin = mean_species - se_species, ymax = mean_species + se_species),
                position = position_dodge(width = 0.9), width = 0.2) +
  geom_text(aes(label = paste0("n=", n_individual), 
                y = mean_species + se_species + errorBarLabelOffset), 
            position = position_dodge(width = 0.9), vjust = -0.5) + 
  theme_minimal() +
  labs(
    title = paste(sep =" ", "Mean Detection Duration for Species",tmp.species),
    x = "Site",
    y = "Mean Detection Duration",
    fill = "Tide Category"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  easy_center_title()
```
```{r Single Species Single Station Plot - ICCB Formatting - INCLUDING NO-DETECTION PERIODS}
# Set plot units
plot.units <- "minutes"

# Select species of interest
#tmp.species <- "Pacific Golden-Plover"
#tmp.species <- "Red-necked Avocet"
tmp.species <- "Pied Stilt"

tmp.receiver <- "Curlew Point"

errorBarLabelOffset = as_units(0.1, plot.units)

# Filter the data to the species and receiver of interest
summ.species_individual <- summ.species %>% 
  filter(
    speciesEN == tmp.species,
    recvDeployName == tmp.receiver) %>%
  # Set plot grouping variables to factors
  ## Factor level order controls the order they appear on the plot 
  mutate(
    tideDiel = factor(tideDiel, levels = c("Diurnal", "Nocturnal")),
    tideHighLow = factor(tideHighLow, levels = c("Low", "High"))) %>% 
  mutate(mean_species = set_units(mean_species, !!plot.units),
         sd_species = set_units(sd_species, !!plot.units),
         se_species = set_units(se_species, !!plot.units))

# ---- Create Grouped Bar Plot ----
p <- ggplot(
  summ.species_individual,
  aes(x = tideHighLow, y = mean_species, fill = tideDiel)) +
  geom_bar(
    stat = "identity", 
    position = position_dodge(width = 0.9), 
    colour = "black") + 
  geom_errorbar(
    aes(ymin = mean_species - se_species, ymax = mean_species + se_species),
    position = position_dodge(width = 0.9), width = 0.2) +
  
  geom_text(aes(label = paste0("n=", n_individual), 
                y = mean_species + se_species + errorBarLabelOffset), 
            position = position_dodge(width = 0.9), vjust = -0.5) +
  
  # 3. Add scale_fill_manual to apply the custom color scheme.
  #    "Diurnal" gets a white fill, "Nocturnal" gets a grey fill.
  scale_fill_manual(values = c("Diurnal" = "white", "Nocturnal" = "grey80")) +
  
  theme_minimal() +
  
  # 4. Update labs to reflect the new plot structure.
  labs(
    title = paste("Mean Detection Duration for", tmp.species, "at", tmp.receiver),
    subtitle = paste("Grouped by tide level and time of day.","n =",max(summ.species_individual$n_individual),"individuals."),
    #x = "Tide Level",
    x = NULL,
    y = "Mean Detection Duration",
    fill = "Time of Day" # More descriptive legend title
  ) +
  
  scale_x_discrete(labels = c("Low" = "Low Tide", "High" = "High Tide")) +
  
  # The x-axis labels ("Low", "High") are short, so we no longer need to angle them.
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
  geom_hline(yintercept = as_units(0, plot.units)) +
  easy_center_title() +
  easy_remove_x_gridlines() +
  easy_x_axis_labels_size(size = 12)

p
```

```{r Single Species-Station - Loop For Plots - ICCB Formatting - INCLUDING NO-DETECTION PERIODS}
plot_dir <- "Plots/Mean_Detection_Plots"

# Set plot units
plot.units <- "minutes"
errorBarLabelOffset = as_units(0.1, plot.units)

tmp.species_list <- c("Pacific Golden-Plover",
                      "Pied Stilt",
                      "Red-necked Avocet")

# Loop through each species of interest
for (tmp.species in tmp.species_list){
  
  tmp.receiver_list <- summ.species %>% 
    filter(speciesEN == tmp.species) %>% 
    pull(recvDeployName) %>% 
    unique()
  
  # Loop through each receiver
  for(tmp.receiver in tmp.receiver_list){
    
    # Filter the species summary data to the species / receiver of interest
    summ.species_individual <- summ.species %>% 
      filter(speciesEN == tmp.species, recvDeployName == tmp.receiver) %>% 
      mutate(mean_species = set_units(mean_species, !!plot.units),
        sd_species = set_units(sd_species, !!plot.units),
        se_species = set_units(se_species, !!plot.units))
    
    # Create the plot
    p <- ggplot(
      summ.species_individual,
      aes(x = tideHighLow, y = mean_species, fill = tideDiel)) +
      geom_bar(
        stat = "identity", 
        position = position_dodge(width = 0.9), 
        colour = "black") + 
      geom_errorbar(
        aes(ymin = mean_species - se_species, ymax = mean_species + se_species),
        position = position_dodge(width = 0.9), width = 0.2) +
      
      geom_text(aes(label = paste0("n=", n_individual), 
                    y = mean_species + se_species + errorBarLabelOffset), 
                position = position_dodge(width = 0.9), vjust = -0.5) +
      
      # 3. Add scale_fill_manual to apply the custom color scheme.
      #    "Diurnal" gets a white fill, "Nocturnal" gets a grey fill.
      scale_fill_manual(values = c("Diurnal" = "white", "Nocturnal" = "grey80")) +
      
      theme_minimal() +
      
      # 4. Update labs to reflect the new plot structure.
      labs(
        title = paste("Mean Detection Duration for", tmp.species, "at", tmp.receiver),
        subtitle = paste("Grouped by tide level and time of day.","n =",max(summ.species_individual$n_individual),"individuals."),
        #x = "Tide Level",
        x = NULL,
        y = "Mean Detection Duration",
        fill = "Time of Day" # More descriptive legend title
      ) +
      
      scale_x_discrete(labels = c("Low" = "Low Tide", "High" = "High Tide")) +
      
      # The x-axis labels ("Low", "High") are short, so we no longer need to angle them.
      theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
            plot.background = element_rect(fill = "white", color = NA)) +
      easy_center_title() +
      easy_remove_x_gridlines() +
      easy_x_axis_labels_size(size = 12) +
      geom_hline(yintercept = as_units(0, plot.units)) +
    
    # Display the plot
    #p
    
    # Save the plot to file
    save.plot(title = p$labels$title, dir_path = paste0("Plots/ICCB_2025/",tmp.species))
  }
}
```

```{r Individual Tag - Mean SEand Bar Plot}
# Filter data for the specific tag
tag.tmp <- 81121

sum.singletag <- df.byTidePeriod %>%
  filter(motusTagID == tag.tmp)

sum.singletag <- sum.singletag %>% 
  group_by(recvDeployName, tideCategory) %>% 
  summarise(meanDuration = mean(detectionDuration),
            sd = sd(detectionDuration, na.rm = TRUE),
            periodCount = n(),
            se = sd/sqrt(periodCount),
            .groups = "drop") %>% 
  ungroup() 

# Create the bar plot with error bars
ggplot(sum.singletag, aes(x = recvDeployName, y = meanDuration, fill = tideCategory)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), colour = "black") + 
  geom_errorbar(aes(ymin = meanDuration - se, ymax = meanDuration + se),
                position = position_dodge(width = 0.9), width = 0.2) +
  theme_minimal() +
  labs(
    title = paste(sep =" ", "Mean Detection Duration for Tag",tag.tmp,"(", tag.species(tag.tmp),")"),
    x = "Site",
    y = "Mean Detection Duration (± SE)",
    fill = "Tide Category"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  easy_center_title()

```



## ---- Plots - Only Tide Periods With Detections ----

```{r Summarise by Species - EXCLUDING NO-DETECTION PERIODS}
# Select species of interest
tmp.species <- c("Red-necked Avocet", "Pacific Golden-Plover", "Pied Stilt")

# Filter by species of interest
df.speciesOfInterest <- df.byTidePeriod %>% 
  filter(speciesEN %in% tmp.species)
  
# Group by tag, receiver, and tidal category, then
# calculate the mean detection duration, SD, and SE
summ.tag_incomplete <- df.speciesOfInterest %>%  
  group_by(recvDeployName, tideCategory, motusTagID, speciesEN) %>% 
    summarise(meanDuration = mean(detectionDuration),
              sd = sd(detectionDuration, na.rm = TRUE),
              periodCount = n(),
              se = sd/sqrt(periodCount),
              .groups = "drop") 

# Remove values with very low period count
#sum.alltags <- sum.alltags %>% filter(
#  periodCount >3
#)

# Group by species, receiver, and tidal category, then
# calculate the mean detection duration, ## not sure how to do error ##
summ.species_incomplete <- summ.tag_incomplete %>% 
  group_by(speciesEN,recvDeployName, tideCategory) %>% 
  summarise(meanDurationSpecies = mean(meanDuration),
            sd = sd(meanDuration),
            individualCount = n(),
            se = sd/sqrt(individualCount),
            .groups = "drop")

```

```{r Plot for Single Species - EXCLUDING NO DETECTION PERIODS}
# Select species of interest
#tmp.species <- "Pacific Golden-Plover"
#tmp.species <- "Red-necked Avocet"
tmp.species <- "Pied Stilt"

errorBarLabelOffset = 0.1

summ.species_individual <- summ.species_incomplete %>% 
  filter(speciesEN == tmp.species)

# Create the bar plot with error bars
ggplot(summ.species_individual, aes(x = recvDeployName, y = meanDurationSpecies, fill = tideCategory)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), colour = "black") + 
  geom_errorbar(aes(ymin = meanDurationSpecies - se, ymax = meanDurationSpecies + se),
                position = position_dodge(width = 0.9), width = 0.2) +
  geom_text(aes(label = paste0("n=", individualCount), 
                y = meanDurationSpecies + se + errorBarLabelOffset), 
            position = position_dodge(width = 0.9), vjust = -0.5) + 
  theme_minimal() +
  labs(
    title = paste(sep =" ", "Mean Detection Duration for Species",tmp.species),
    x = "Site",
    y = "Mean Detection Duration (± SE)",
    fill = "Tide Category"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  easy_center_title()
```

# ==== MISC ====

```{r Test Producing Complete (All Tide Period) Table For Individual Tag}
# By complete, I mean every tide period between the first and last time the 
# tag was detected, including those where the tag was NOT detected.
# (Only values if tideID where the tag was detected are present in df.alltags)
#tmp.tag = 43296 %>% as.factor()
tmp.tag = 43296
df.tmp <- df.byTidePeriod %>% filter(motusTagID == tmp.tag) 

## Start with single station
tmp.receiver <- "Fullerton Entrance"
df.tmp <- df.tmp %>% filter(recvDeployName == "Fullerton Entrance")

## Filter unique tidal periods by individual tag detections
tideData = readRDS("Data/tideData.rds")

tide.tmp <- tideData %>% filter(
  tideDateTimeAus >= tag.firstDetection(tmp.tag),
  tideDateTimeAus <= tag.lastDetection(tmp.tag)
)

grid.test <- expand.grid(
  motusTagID = tmp.tag,
  recvDeployName = tmp.receiver,
  tideID = tide.tmp$tideID
)

grid.test <- grid.test %>% mutate(
  motusTagID = as_factor(motusTagID)
)

join.test <- left_join(grid.test, df.tmp,
                       by = c("motusTagID", "tideID", "recvDeployName")) %>% 
  mutate(detectionDuration = ifelse(is.na(detectionDuration), 0, detectionDuration))
```

```{r BROKEN Three-way Repeated Measures ANOVA}
# Broken / old - not worth fixing rn
# Get statistical summary
sum.species <- sum.alltags %>% 
  group_by(speciesEN, tideCategory, recvDeployName) %>% 
  get_summary_stats(meanDuration, type = "mean_se")

## Filter out rows with detection during a single period (SE = NA) or 2 periods
sum.anova <- sum.alltags %>% 
  filter(#is.na(se)==FALSE)
    periodCount > 2)

# Check for outliers
outliers <- sum.anova %>% 
  group_by(speciesEN, tideCategory, recvDeployName) %>% 
  identify_outliers(meanDuration)

#### Have not implemented code to remove outliers ####
### After removing the single period rows (NA se), none of the outliers
### are extreme###

# Get summary statistics for each species
summary_stats <- sum.anova %>% 
  group_by(speciesEN, recvDeployName, tideCategory) %>% 
  get_summary_stats(meanDuration, type = "mean_se")

# Filter out combinations of species / category / receiver with n < 3
valid_groups <- sum.anova %>%
  group_by(speciesEN, recvDeployName, tideCategory) %>%
  summarise(n = n(), .groups = 'drop') %>%
  filter(n >= 3)

# Join valid groups back to the original dataset to filter only valid motusTagID
final_data <- sum.anova %>%
  semi_join(valid_groups, by = c("speciesEN", "recvDeployName", "tideCategory"))

# Check normality assumption
not_normal <- final_data %>% 
  group_by(speciesEN, tideCategory, recvDeployName) %>% 
  shapiro_test(meanDuration) %>% 
  filter(p < 0.05)

## Remove rows that are not normal
# Step 1: Extract the non-normal combinations
non_normal_combinations <- not_normal %>%
  select(speciesEN, tideCategory, recvDeployName)

# Step 2: Filter out non-normal combinations from final_data
cleaned_final_data <- final_data %>%
  anti_join(non_normal_combinations, by = c("speciesEN", "tideCategory", "recvDeployName"))

## To add: qq plot for normality assessment ##

# Coerce grouping variables to factor
cleaned_final_data <- cleaned_final_data %>% 
  mutate(recvDeployName = as.factor(recvDeployName),
         speciesEN = as.factor(speciesEN))

# ANOVA
res.aov <- anova_test(
  data = cleaned_final_data, dv = meanDuration, wid = motusTagID,
  within = c(speciesEN, recvDeployName, tideCategory)
)

```

```{r Attempt to Perform for a Single Species}
#tmp.species <- "Pacific Golden-Plover"
#tmp.species <- "Red-necked Avocet"
tmp.species <- "Pied Stilt"

cleaned_final_data_species <- cleaned_final_data %>% 
  filter(speciesEN == tmp.species)

table(cleaned_final_data_species$recvDeployName, cleaned_final_data_species$tideCategory)

# ANOVA
res.aov <- anova_test(
  data = cleaned_final_data_species, dv = meanDuration, wid = motusTagID,
  within = c(recvDeployName, tideCategory)
)

```

```{r Chat GPT Test - Plot for detection duration averages by species}
# Step 1: Compute the average detection duration per tag for each site × tide category
df.avg_tag <- df.byTidePeriod %>%
  group_by(motusTagID, recvDeployName, tideCategory) %>%
  summarise(avg_detection_duration = mean(detectionDuration), .groups = "drop")

# Step 2: Compute the average detection duration per species for each site × tide category
df.avg_species <- df.avg_tag %>%
  left_join(df.byTidePeriod %>% select(motusTagID, speciesEN) %>% distinct(), by = "motusTagID") %>%
  group_by(speciesEN, recvDeployName, tideCategory) %>%
  summarise(
    avg_species_detection = mean(avg_detection_duration),
    se = sd(avg_detection_duration) / sqrt(n()),  # Standard error for error bars
    .groups = "drop"
  )

# Step 3: Plot the results
ggplot(df.avg_species, aes(x = tideCategory, y = avg_species_detection, fill = speciesEN)) +
  geom_bar(stat = "identity", position = position_dodge(), colour = "black") +
  geom_errorbar(aes(ymin = avg_species_detection - se, ymax = avg_species_detection + se),
                position = position_dodge(width = 0.9), width = 0.2) +
  facet_wrap(~recvDeployName) +  # Facet by site
  theme_minimal() +
  labs(
    title = "Average Detection Duration by Species, Site, and Tide Category",
    x = "Tide Category",
    y = "Average Detection Duration",
    fill = "Species"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

